apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  namespace: openshift-distributed-tracing
spec:
  displayName: Red Hat OpenShift distributed tracing platform
status: 
  phase: Succeeded