---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: service-mesh-policy-placement
  namespace: policies
spec:
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchExpressions:
            - key: group
              operator: In
              values:
                - "IT"
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: service-mesh-policy-placement
  namespace: policies
placementRef:
  name: service-mesh-policy-placement
  apiGroup: cluster.open-cluster-management.io
  kind: Placement
subjects:
  - name: servicemesh-policy-set
    apiGroup: policy.open-cluster-management.io
    kind: PolicySet
  
