apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: test-application-set
  namespace: openshift-gitops
  creationTimestamp: 2023-11-18T00:21:28Z
  generation: 1
  resourceVersion: "1571410"
  uid: f9deea9c-379e-4dcd-9788-23367c707751
spec:
  generators:
    - clusterDecisionResource:
        configMapRef: acm-placement
        labelSelector:
          matchLabels:
            cluster.open-cluster-management.io/placement: test-application-set-placement
        requeueAfterSeconds: 180
  template:
    metadata:
      name: test-application-set-{{name}}
      labels:
        velero.io/exclude-from-backup: "true"
    spec:
      destination:
        namespace: openshift-gitops
        server: "{{server}}"
      project: default
      source:
        path: gitops
        repoURL: https://github.com/redhat-telco-adoption/acm-gitops
        targetRevision: main
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - PruneLast=true
status:
  conditions:
    - lastTransitionTime: 2023-11-18T00:21:28Z
      message: Successfully generated parameters for all Applications
      reason: ApplicationSetUpToDate
      status: "False"
      type: ErrorOccurred
    - lastTransitionTime: 2023-11-18T00:21:28Z
      message: Successfully generated parameters for all Applications
      reason: ParametersGenerated
      status: "True"
      type: ParametersGenerated
    - lastTransitionTime: 2023-11-18T00:21:28Z
      message: ApplicationSet up to date
      reason: ApplicationSetUpToDate
      status: "True"
      type: ResourcesUpToDate
---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: test-application-set-placement
  namespace: openshift-gitops
  creationTimestamp: 2023-11-16T23:36:08Z
  generation: 1
  resourceVersion: "1336562"
  uid: 4242ddd5-5059-40c8-9edc-179c6c43b248
spec:
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchExpressions:
            - key: vendor
              operator: In
              values:
                - OpenShift
  tolerations:
    - key: cluster.open-cluster-management.io/unreachable
      operator: Exists
    - key: cluster.open-cluster-management.io/unavailable
      operator: Exists
status:
  conditions:
    - lastTransitionTime: 2023-11-16T23:36:08Z
      message: Placement configurations check pass
      reason: Succeedconfigured
      status: "False"
      type: PlacementMisconfigured
    - lastTransitionTime: 2023-11-17T20:29:24Z
      message: All cluster decisions scheduled
      reason: AllDecisionsScheduled
      status: "True"
      type: PlacementSatisfied
  numberOfSelectedClusters: 1
