apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: servicemesh-controlplane-applicationset
  namespace: openshift-gitops
spec:
  generators:
  - clusterDecisionResource:
      configMapRef: acm-placement
      labelSelector:
        matchLabels:
          cluster.open-cluster-management.io/placement: all-clusters
      requeueAfterSeconds: 180
  template:
    metadata:
      labels:
        velero.io/exclude-from-backup: "true"
      name: servicemesh-controlplane-applicationset-{{name}}
    spec:
      destination:
        namespace: not-used
        server: '{{server}}'
      project: default
      source:
        path: gitops/servicemesh/controlplane
        repoURL: https://github.com/redhat-telco-adoption/acm-gitops
        targetRevision: main
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
        - PruneLast=true
